inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: false

Style/ClassCheck:
  Enabled: false
  # we don't care about kind_of? vs is_a?

Style/StringLiterals:
  Enabled: false

Naming/FileName:
  Enabled: false

Style/RedundantException:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

# Github's PR width is 120 characters
Layout/LineLength:
  Max: 120
  AllowURI: true

Metrics/AbcSize:
  Description: A calculated magnitude based on number of assignments, branches, and
    conditions.
  Enabled: true
  Max: 30
